@startuml
actor :Student: as A

A --> (Login)
A --> (Logout)
A --> (Register)
A --> (Search \n course)
A --> (Enrol in \n course)
A --> (Unenrol \n from course)
A --> (Provide \n feedback)
A --> (Read \n material)

@enduml
